language: node_js
node_js:
  - lts/*
cache: npm install
addons:
  sonarcloud:
    organisation: tradetrust
jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test-coverage
        - sonar-scanner
stages:
  - test
  - integration